### ISSUE TITLE
extractify: command not found | extractify: command not found 

### ISSUE THREAD

**Issue by a1k-ghaz1** [SharokhAtaie/extractify#1]
**┌──(ma㉿Windows11)-[~]
└─$ go install github.com/SharokhAtaie/extractify@latest
go: finding module for package github.com/logrusorgru/aurora/v4
go: found github.com/logrusorgru/aurora/v4 in github.com/logrusorgru/aurora/v4 v4.0.0
# internal/goarch
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# internal/coverage/rtcov
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# internal/godebugs
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# internal/unsafeheader
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# internal/goos
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# internal/race
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# unicode/utf8
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# internal/cpu
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# runtime/internal/syscall
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# internal/goexperiment
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# unicode
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# container/list
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# runtime/internal/atomic
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# internal/itoa
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# sync/atomic
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# math/bits
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# crypto/internal/alias
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# unicode/utf16
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# vendor/golang.org/x/crypto/internal/alias
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# vendor/golang.org/x/crypto/cryptobyte/asn1
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# encoding
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# internal/nettrace
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# log/internal
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# github.com/projectdiscovery/gologger/levels
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# crypto/subtle
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# crypto/internal/boring/sig
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# github.com/pierrec/lz4/v4/internal/lz4errors
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# github.com/dsnet/compress/bzip2/internal/sais
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# github.com/dsnet/compress/internal
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# github.com/ulikunitz/xz/internal/hash
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# golang.org/x/net/internal/iana
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# golang.org/x/exp/maps
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# golang.org/x/net/html/atom
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# golang.org/x/exp/constraints
compile: version "go1.21.6" does not match go tool version "go1.22.0"
# github.com/projectdiscovery/utils/race
compile: version "go1.21.6" does not match go tool version "go1.22.0"

┌──(ma㉿Windows11)-[~]
└─$ extractify -h
extractify: command not found

┌──(ma㉿Windows11)-[~]
└─$ subfinder

               __    _____           __
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/

                projectdiscovery.io

[INF] Current subfinder version v2.6.5 (latest)
[FTL] Program exiting: no input list provided

┌──(ma㉿Windows11)-[~]
└─$**

**Comment by SharokhAtaie** [comment]
Hello @a1k-ghaz1,

I have installed and successfully run it on Windows and Linux using the latest version of Golang: 
`go version go1.22.0 windows/amd64`
`go version go1.22.0 linux/amd64`

Please check your GOPATH or consider reinstalling Golang on your system.

![Screenshot 2024-02-15 133619](https://github.com/SharokhAtaie/extractify/assets/94289484/e7b146d8-06da-4c32-87ba-380779940052)


![Screenshot 2024-02-15 133547](https://github.com/SharokhAtaie/extractify/assets/94289484/3d2824d6-7fd5-472d-98fc-0d36255ed1b4)
